### ISSUE TITLE
[Bug]: vim.lsp.util.get_progress_messages is deprecated in nvim >= 0.10

### ISSUE THREAD

**Issue by fbearoff** [chrisgrieser/nvim-dr-lsp#1]
### Bug Description

On nightly the deprecation notice `vim.lsp.util.get_progress_messages is deprecated, use vim.lsp.status instead. :help deprecated
This feature will be removed in Nvim version 0.11.0` is shown

### neovim version

```Text
NVIM v0.10.0-dev-546+g3bf887f6e
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
Ah, didn't notice since I am not on nightly. Thanks, should be fixed

**Comment by fbearoff** [comment]
Still getting the notice, I think it is this line now https://github.com/chrisgrieser/nvim-dr-lsp/blob/43cdaba48f1ece12e4cbd22c553f99b9c1a1d776/lua/dr-lsp.lua#L49

**Comment by chrisgrieser** [comment]
oh thx

**Comment by fbearoff** [comment]
Still broken, flipping the logic fixes it 

``` 
(vim.version().minor > 9 and vim.version().major == 0) and vim.lsp.status() or vim.lsp.util.get_progress_messages()
```

**Comment by chrisgrieser** [comment]
thx. Next time, feel free to directly make a PR, if you found the issue already anyway?
